### PR TITLE
Implements misc. changes from issue #2

### LINKED ISSUE #2: Misc. Things
There were some things, that came to my mind when looking at the code:
- **Tests**: I know this is probably a pain no one wants to have, but tests would be very nice.
Why are tests good? They help building trust in your code and also when some random dude (like me) comes up and pushes some pull request you have at least some sort of orientation to find out if there were breaking changes made.

- **Type-hints**: Same thing as it is for the tests. It gains trust and also you could hint that only pytroch dataloader should be inputted in your function.
If you use type-hints IDE would read them and warn the user of your library that he is about to input something not wanted in your function. 

- **Regarding your Algorithm**: You have implemented some redudant things here which are not that necessary to do acutally.
I think with some refactoring this would be even more readable although your variable-naming is very point on and does the job for the most part. But let me show two small things:

1. Line 26 and 27 are redudant. Why?
You have no gain in information with these lines since this set is already given with the hash-dictionary `hasd_1` and `hasd_2`. Dictionarys only allow only unique keys and you choose the data-hash as key (which is nice imho). So this:
```python
# Unique hashes
set_hash_loader1 = set(hash_loader1)
set_hash_loader2 = set(hash_loader2)
```
could be re-written as
```python
# Unique hashes
set_hash_loader1 = set(hasd_1.keys())
set_hash_loader2 = set(hasd_2.keys())
```
This would not make that much sense because you check later (in line 30) if hashs overlap from the dataloader.
Dictionarys provide the same interface for entry-checking as sets. So this would do the as well:
```python
for hsh in hasd_1.keys():
    if hsh in hasd_2:
        ....
```
So the main useage of `set_hash_loader`s were eliminated you could eliminate the variables `hash_loader1` and `hash_loader2` since they are used to create the original sets.

This alone should significantly drop the memory useage. Maybe this is not relevant when handeling small dataset (maybe up to 10.000 entries) but when looking at bigger datasets this could break your algorithm.

2. There is some sort of redundancy and I think mash-up of index in the lines 9 to 24.
The variable `index` is used to indicate the position (or index lol) in of a dataloader. My problem is that I do not understand what you want to generalize with line 9. To put it in words of what you are doing is: iterate over  both dataloader and adding an index to them which is used for their separation. The separation is that you want to do different things to the dataloader-1 and dataloader-2. But you are ending up doing the same thing for both of them. This is a big hint that here is something off and need to be worked on. This is the point when I would consider extracting some functionality into new function which will be called when needed.

----

Positive things:

- As I stated above, your variable-naming is on point and that alone is a huge advantage in undersanding what your code is intended to do for me.
- Your README is short and significant here because one the hand you explain the usage as well as the installation. At the other hand you hand out the debugging-code someone could use to double-check the results of your algorithm. Your example-output is very valuable since are "only" working with index in the dataloader. I think the example is also well chosen.
- You provided a licence which always helps.

-----

I'd like to implement those things I mentioned above. But if you want to try it yourself (maybe as practice or something) I'd be happy to review your implementation again, when you are ready ^^

### PR DESCRIPTION
**Pull request by blos**
Resolves #2

### CODE REVIEW

**Comment by LaihoE** [comment]
Thanks for the pull request. I'm sorry but there seems to be something off with the implementation. One thing I noticed is that the indexes are incorrect with batch size > 1, something I feel is important. The library would preferably not require any changes from the users normal code. This should be an easy fix, just check the size from the batch, but unfortunately I was also able to find some nasty bug where some datasets would give spills even if there are none. This is nasty because I'm not able to properly replicate it, sometimes it works sometimes it doesn't, just happen to find it using a real world dataset. Maybe it has to do with the types in the dataset? I'm not really sure but couldn't find any good reason after some debugging.

**Comment by blos** [comment]
Regarding the part with incorrect results with batch-size > 1: I will look into that.

But regarding the detections of spills if there should be none: I think this should be a different issue. I suspect that there is somethign going on with the hash-function and how the sha1 interacts with the hash-function of a dictionary or a set.

**Comment by LaihoE** [comment]
Sorry for any time wasted. I went back and implemented type-hints and removed the redundancy. I'm really not sure why I had included the redundant stuff in the first place, thank you for pointing it out. This version does also not suffer from the strange bug.
On the other hand, the tests are very welcome. Maybe you could create a new PR with them?

**Comment by blos** [comment]
Sure, I will open a new PR.

**Pull request closed without merging**
